kcf_follow:
  ros__parameters:
    rgb_topic: /ascamera_hp60c/camera_publisher/rgb0/image
    depth_topic: /ascamera_hp60c/camera_publisher/depth0/image_raw
    cmd_vel_topic: /cmd_vel
    joy_state_topic: /JoyState
    image_width: 640
    image_height: 480
    target_distance_mm: 500.0
    distance_deadband_mm: 40.0
    center_deadband_px: 45.0
    max_linear_speed: 0.8
    max_angular_speed: 0.8
    linear_kp: 0.0005
    linear_ki: 0.0
    linear_kd: 0.0005
    angular_kp: 0.018
    angular_ki: 0.0
    angular_kd: 0.005
    show_window: true
    flip_image: false
